### ISSUE TITLE
节点如何查看时候正常运行

### ISSUE THREAD

**Issue by lvjie871211** [glzjin/ssshell-jar#13]
你好，想问下，我按照你的教程，搭建好了前台+后台，担我无法正常使用SS，请问我如何查看后台SS服务时候正确运行

**Comment by j0hnnie** [comment]
同问，之前shadowsock原版还有带一个sserver.log可以查看，这个我完全不晓得哪里去看？

**Comment by glzjin** [comment]
java -jar ssshell.jar
glzjin
2016年5月12日 下午2:26，j0hnnie <notifications@github.com>写道：同问，之前shadowsock原版还有带一个sserver.log可以查看，这个我完全不晓得哪里去看？

**Comment by lvjie871211** [comment]
你好，我运行报错这个
[root@XYZ-NEW ssshell]# java -jar ssshell.jar
5 12, 2016 5:02:44 午後 com.mchange.v2.log.MLog 
情報: MLog clients using java 1.4+ standard logging.
5 12, 2016 5:02:45 午後 com.mchange.v2.c3p0.C3P0Registry 
情報: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
[info][2016-05-12 17:02:45]Connecting to mysql....
5 12, 2016 5:02:45 午後 com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
情報: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 2spfvd9g19i1kqxeef7gx|243c4f91, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 2spfvd9g19i1kqxeef7gx|243c4f91, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://XXX.XXX.XXX.XXX sspanel?autoReconnect=true, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 120, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 10, maxStatements -> 50, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]




5 12, 2016 5:05:49 午後 com.mchange.v2.resourcepool.BasicResourcePool 
警告: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@28f8b341 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
        at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)

**Comment by glzjin** [comment]
不能连接数据库，没开数据库端口？
glzjin
2016年5月12日 下午4:07，lvjie871211 <notifications@github.com>写道：你好，我运行报错这个
[root@XYZ-NEW ssshell]# java -jar ssshell.jar
5 12, 2016 5:02:44 午後 com.mchange.v2.log.MLog 
情報: MLog clients using java 1.4+ standard logging.
5 12, 2016 5:02:45 午後 com.mchange.v2.c3p0.C3P0Registry 
情報: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
[info][2016-05-12 17:02:45]Connecting to mysql....
5 12, 2016 5:02:45 午後 com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
情報: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 2spfvd9g19i1kqxeef7gx|243c4f91, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 2spfvd9g19i1kqxeef7gx|243c4f91, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://XXX.XXX.XXX.XXX sspanel?autoReconnect=true, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 120, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 10, maxStatements -> 50, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=***, password=***}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]

5 12, 2016 5:05:49 午後 com.mchange.v2.resourcepool.BasicResourcePool 
警告: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@28f8b341 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
        at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:790)
        at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:44)
        at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)

**Comment by lvjie871211** [comment]
是在同一台电脑上的，以下是目前的端口
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      32595/sshd          
tcp        0      0 0.0.0.0:3306                0.0.0.0:*                   LISTEN      12317/mysqld        
tcp        0      0 0.0.0.0:80                  0.0.0.0:*                   LISTEN      15415/nginx         
tcp        0      0 :::22                       :::*                        LISTEN      32595/sshd          
udp        0      0 0.0.0.0:68                  0.0.0.0:*                               914/dhclient        
udp        0      0 127.0.0.1:18120             0.0.0.0:*                               12606/radiusd       
udp        0      0 0.0.0.0:34155               0.0.0.0:*                               12606/radiusd       
udp        0      0 10.21.0.153:123             0.0.0.0:*                               1479/ntpd           
udp        0      0 127.0.0.1:123               0.0.0.0:*                               1479/ntpd           
udp        0      0 0.0.0.0:123                 0.0.0.0:*                               1479/ntpd           
udp        0      0 0.0.0.0:1812                0.0.0.0:*                               12606/radiusd       
udp        0      0 0.0.0.0:1813                0.0.0.0:*                               12606/radiusd       
udp        0      0 0.0.0.0:1814                0.0.0.0:*                               12606/radiusd       
udp        0      0 fe80::1eff:febb:6:123       :::*                                    1479/ntpd           
udp        0      0 ::1:123                     :::*                                    1479/ntpd           
udp        0      0 :::123                      :::*                                    1479/ntpd

**Comment by glzjin** [comment]
那个错误提示是无法连接数据库，请自行检查填写，如果填写的数据库地址是域名，请检查3306是否开放，lnmp某人是关闭的。
