### ISSUE TITLE
 java -jar ssshell.jar  报错网上查了原因是libpcap没安装，但是很早就安装过了，不知道什么原因？

### ISSUE THREAD

**Issue by dvb0036** [glzjin/ssshell-jar#17]
[root@localhost ssshell]# java -jar ssshell.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
        at com.slytechs.library.NativeLibrary.dlopen(Native Method)
        at com.slytechs.library.NativeLibrary.<init>(Unknown Source)
        at com.slytechs.library.JNILibrary.<init>(Unknown Source)
        at com.slytechs.library.JNILibrary.loadLibrary(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at org.jnetpcap.nio.JMemory.<clinit>(Unknown Source)
        at Shadowsocks_Shell.Main.<clinit>(Main.java:62)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
[root@localhost ssshell]# yum -y install libpcap
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.scalabledns.com
 * rpmforge: mirror.hmc.edu
 * updates: centos.mirror.ndchost.com
Package 14:libpcap-1.4.0-4.20130826git2dbcaa1.el6.i686 already installed and latest version

**Comment by glzjin** [comment]
下载我给的那两个so文件
glzjin
2016年5月17日 下午7:34，dvb0036 <notifications@github.com>写道：[root@localhost ssshell]# java -jar ssshell.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
        at com.slytechs.library.NativeLibrary.dlopen(Native Method)
        at com.slytechs.library.NativeLibrary.(Unknown Source)
        at com.slytechs.library.JNILibrary.(Unknown Source)
        at com.slytechs.library.JNILibrary.loadLibrary(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at org.jnetpcap.nio.JMemory.(Unknown Source)
        at Shadowsocks_Shell.Main.(Main.java:62)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
[root@localhost ssshell]# yum -y install libpcap
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile

base: mirror.keystealth.orgepel: mirror.sfo12.us.leaseweb.netextras: mirror.scalabledns.comrpmforge: mirror.hmc.eduupdates: centos.mirror.ndchost.com
Package 14:libpcap-1.4.0-4.20130826git2dbcaa1.el6.i686 already installed and latest version
