### ISSUE TITLE
执行java -jar ssshell.jar 报错

### ISSUE THREAD

**Issue by xiadena** [glzjin/ssshell-jar#6]
Exception in thread "main" java.lang.UnsupportedClassVersionError: Shadowsocks_Shell/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

请问问题出在哪

**Comment by lion1991** [comment]
之前的配置文件有地址吗?我刚安装 但是有些文件无法下载.

**Comment by xiadena** [comment]
@lion1991 下载地址加参数--no-check-certificate

**Comment by glzjin** [comment]
yum update
glzjin
2016年5月6日 下午10:15，xiadena <notifications@github.com>写道：@lion1991 下载地址加参数--no-check-certificate

**Comment by lion1991** [comment]
@xiadena 加了参数试了几个地方的主机都不行,连接超时...-.-...
